### ISSUE TITLE
Request for Generating Links to Contributors' GitHub Pages

### ISSUE THREAD

**Issue by kowyo** [xhofe/gh-contributors#1]
Hello, thank you so much for the wonderful project you make.

May I ask you is there any way I could generate link for every contributor's avatar that links to their GitHub Page. I know it is not supported in Markdown, but is a there a way implemented by html or css? I wish every contributor in the repo is worth  more than an avatar when the user wants to know them.

**Comment by xhofe** [comment]
you can use iframe, just replace the `api` with `iframe`:
```
https://contrib.nn.ci/iframe?repo=[user/repo]
```
such as: 

https://contrib.nn.ci/iframe?repo=alist-org/alist&repo=alist-org/alist-web&repo=alist-org/docs&radius=22

**Comment by xiln7** [comment]
I find that it is supported when you open in a new tab. But could I embed this to my html or markdown (markdown supports html).

**Comment by kowyo** [comment]
Thank you for the quick reply, it works great!
