### ISSUE TITLE
Suggestion for iframe background transparency and content alignment

### ISSUE THREAD

**Issue by kowyo** [xhofe/gh-contributors#2]
I would like to know if it is possible to have a transparent background or have it follow the color scheme, while aligning the content in the middle. It appears that these parameters are not readily available. 

I would greatly appreciate any assistance or guidance you can provide! ❤️

I have attached an image for reference:

<img width="847" alt="image" src="https://github.com/xhofe/gh-contributors/assets/110339237/80dfab09-1c84-417c-b078-b7281019f228">

**Comment by kowyo** [comment]
I am using iframe in the picture above.

**Comment by w3teal** [comment]
Why using iframe? You can using img and it basically has transparent background.

**Comment by kowyo** [comment]
Yes, but only iframe allows you to click the avatar and open the profile directly.

**Comment by w3teal** [comment]
I was embed the svg using iframe, but that was work transparently.
What iframe code you use?
![screencapture-file-F-Fun-with-HTML-Original-Test-hello-2-html-2024-06-06-13_22_10](https://github.com/xhofe/gh-contributors/assets/143163098/a6b34119-34b6-4de7-acf1-094d62b6567d)

**Comment by kowyo** [comment]
Would you like to give me a referenced link? I used the link as author suggested: https://github.com/xhofe/gh-contributors/issues/1#issuecomment-1878640289

**Comment by w3teal** [comment]
I just use the default svg (https://contrib.nn.ci/api?repo=docsifyjs/awesome-docsify) and it just work.

**Comment by kowyo** [comment]
Thank you @LIGMATV! It does work. Now I start to wonder why it didn't work four months ago. Will close the issue after further confirmation.
