### ISSUE TITLE
Bug: new contributor doesn't show up

### ISSUE THREAD

**Issue by kowyo** [xhofe/gh-contributors#4]
There is a [new contributor](https://github.com/oldkingOK) in our [repo](https://github.com/HITSZ-OpenAuto/MOOC)

But the https://contrib.nn.ci doesn't show his name.

**Comment by xhofe** [comment]
Contributors are not updated in real time but cached for a while, and it should be fine now

**Comment by kowyo** [comment]
Can I know how often the updates are?

**Comment by xhofe** [comment]
https://github.com/xhofe/gh-contributors/blob/53cd67e33b7cdfdb8854aed857d8d02eb3bf3605/app/api/github.ts#L9

Normally it is one day, but there may be some delays because the website also uses cloudflare CDN

**Comment by kowyo** [comment]
Thank you!
