### ISSUE TITLE
error on line 169 at column 5554: AttValue: ‘ expected

### ISSUE THREAD

**Issue by kowyo** [xhofe/gh-contributors#5]
![image](https://github.com/xhofe/gh-contributors/assets/110339237/aa4c2451-e25f-49d3-8f1b-c0002aa589ce)

I find this error in both your and our project, I don’t know if it’s related to safari browser.

**Comment by xhofe** [comment]
This issue appears to be caused by GitHub not fully requesting the image during the transfer process, resulting in the incorrect result being cached. The original link is functioning as expected:
https://contrib.nn.ci/api?repo=alist-org/alist&repo=alist-org/alist-web&repo=alist-org/docs

**Comment by kowyo** [comment]
Thanks for your professional response! I will close this issue.
