### ISSUE TITLE
Contributors are not listed.

### ISSUE THREAD

**Issue by kowyo** [xhofe/gh-contributors#6]
Hi! I really love your product. I have opened a few issues here and really appreciate that you can reply to me.

Recently I have encountered a new issue. So now I have a [repo](https://github.com/HITSZ-OpenAuto/HITSZ-OpenAuto) that GitHub list its contributors all the time. Due to license issue we remove its sensitive commit months before. Now I try to record its contributor using your product: [gh-contributors](https://github.com/xhofe/gh-contributors).

I don't know how your product work due to my lack knowledge of front-end dev. I have tried to commit with these contributors using co-author commit. But I still found that they doesn't appear.

Effect:

![](https://contrib.nn.ci/api?repo=HITSZ-OpenAuto/HITSZ-OpenAuto)

What I expect:

![](https://contrib.nn.ci/api?repo=noname7321/HITSZ-OpenAuto)

Actually I am Chinese too, so I don't know if you mind we communicating in Chinese :)

你好！我很热爱你的产品。很感激你之前能够回复我的 issue。

最近我遇到了一个新问题。现在我有一个仓库，GitHub可以列出它的贡献者。由于许可问题，我在几个月前删除了一些敏感的提交。现在我尝试使用你们的产品[gh-contributors](https://github.com/xhofe/gh-contributors) 显示贡献者图片。

因为我不是很懂前端开发，所以我也不太清楚为什么没有显示出来。我已经尝试过使用协作者提交来提交这些贡献者，但我发现他们仍然没有出现。

**Comment by xhofe** [comment]
The data of contributors displayed with our tool is sourced from [the official GitHub API](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-contributors):

```
https://api.github.com/repos/HITSZ-OpenAuto/HITSZ-OpenAuto/contributors?per_page=100
```
And you can see that there is only one contributor in the response from the official GitHub API.

```json
[
    {
        "login": "kowyo",
        "id": 110339237,
        "node_id": "U_kgDOBpOkpQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/110339237?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kowyo",
        "html_url": "https://github.com/kowyo",
        "followers_url": "https://api.github.com/users/kowyo/followers",
        "following_url": "https://api.github.com/users/kowyo/following{/other_user}",
        "gists_url": "https://api.github.com/users/kowyo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kowyo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kowyo/subscriptions",
        "organizations_url": "https://api.github.com/users/kowyo/orgs",
        "repos_url": "https://api.github.com/users/kowyo/repos",
        "events_url": "https://api.github.com/users/kowyo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kowyo/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 1
    }
]
```
It may be due to:
> This endpoint may return information that is a few hours old because the GitHub REST API caches contributor data to improve performance.

Otherwise, perhaps we won't be able to resolve this issue, and you can consult the GitHub documentation.

**Comment by kowyo** [comment]
Thank you. I believe it's an issue or confusion of GitHub REST API so it is not related to your project now as it shows graph in the web page, but displays the wrong info in API. You can close this issue if you wish.

**Comment by xhofe** [comment]
Close it due to out-of-scope
